name: Main

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        ./build.sh
